/* Generated by Yosys 0.60+70 (git sha1 8101c87fa, g++ 13.3.0-6ubuntu2~24.04 -fPIC -O3) */

module design6_seq(clk, rst_n, start, A, B, C, D, F, valid);
  input clk;
  wire clk;
  input rst_n;
  wire rst_n;
  input start;
  wire start;
  input [3:0] A;
  wire [3:0] A;
  input [3:0] B;
  wire [3:0] B;
  input [3:0] C;
  wire [3:0] C;
  input [3:0] D;
  wire [3:0] D;
  output [5:0] F;
  wire [5:0] F;
  output valid;
  wire valid;
  wire [5:0] _000_;
  wire [5:0] _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire [5:0] acc_reg;
  wire [2:0] current_state;
  wire [2:0] next_state;
  sky130_fd_sc_hd__nor2_1 _058_ (
    .A(current_state[1]),
    .B(current_state[0]),
    .Y(_015_)
  );
  sky130_fd_sc_hd__a21o_1 _059_ (
    .A1(current_state[1]),
    .A2(current_state[0]),
    .B1(current_state[2]),
    .X(_016_)
  );
  sky130_fd_sc_hd__nor2_1 _060_ (
    .A(_015_),
    .B(_016_),
    .Y(next_state[1])
  );
  sky130_fd_sc_hd__nand2b_1 _061_ (
    .A_N(current_state[2]),
    .B(current_state[1]),
    .Y(_017_)
  );
  sky130_fd_sc_hd__nor3b_1 _062_ (
    .A(current_state[0]),
    .B(current_state[2]),
    .C_N(current_state[1]),
    .Y(_018_)
  );
  sky130_fd_sc_hd__o21ai_0 _063_ (
    .A1(current_state[2]),
    .A2(start),
    .B1(_015_),
    .Y(_019_)
  );
  sky130_fd_sc_hd__o21ai_0 _064_ (
    .A1(current_state[0]),
    .A2(_017_),
    .B1(_019_),
    .Y(next_state[0])
  );
  sky130_fd_sc_hd__nor3b_1 _065_ (
    .A(current_state[1]),
    .B(current_state[0]),
    .C_N(current_state[2]),
    .Y(_020_)
  );
  sky130_fd_sc_hd__or3b_1 _066_ (
    .A(current_state[1]),
    .B(current_state[0]),
    .C_N(current_state[2]),
    .X(_021_)
  );
  sky130_fd_sc_hd__and3b_1 _067_ (
    .A_N(current_state[2]),
    .B(current_state[0]),
    .C(current_state[1]),
    .X(_022_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _068_ (
    .A(_020_),
    .SLEEP(_022_),
    .X(next_state[2])
  );
  sky130_fd_sc_hd__and3_1 _069_ (
    .A(A[3]),
    .B(_017_),
    .C(_021_),
    .X(_023_)
  );
  sky130_fd_sc_hd__and2_0 _070_ (
    .A(C[3]),
    .B(_022_),
    .X(_024_)
  );
  sky130_fd_sc_hd__a22o_1 _071_ (
    .A1(B[3]),
    .A2(_018_),
    .B1(_020_),
    .B2(D[3]),
    .X(_025_)
  );
  sky130_fd_sc_hd__o31a_1 _072_ (
    .A1(_023_),
    .A2(_024_),
    .A3(_025_),
    .B1(acc_reg[3]),
    .X(_026_)
  );
  sky130_fd_sc_hd__nand3_1 _073_ (
    .A(A[2]),
    .B(_017_),
    .C(_021_),
    .Y(_027_)
  );
  sky130_fd_sc_hd__nand2_1 _074_ (
    .A(D[2]),
    .B(_020_),
    .Y(_028_)
  );
  sky130_fd_sc_hd__a22oi_1 _075_ (
    .A1(B[2]),
    .A2(_018_),
    .B1(_022_),
    .B2(C[2]),
    .Y(_029_)
  );
  sky130_fd_sc_hd__nand3_1 _076_ (
    .A(_027_),
    .B(_028_),
    .C(_029_),
    .Y(_030_)
  );
  sky130_fd_sc_hd__and2_0 _077_ (
    .A(acc_reg[2]),
    .B(_030_),
    .X(_031_)
  );
  sky130_fd_sc_hd__a32oi_1 _078_ (
    .A1(A[1]),
    .A2(_017_),
    .A3(_021_),
    .B1(_022_),
    .B2(C[1]),
    .Y(_032_)
  );
  sky130_fd_sc_hd__a22oi_1 _079_ (
    .A1(B[1]),
    .A2(_018_),
    .B1(_020_),
    .B2(D[1]),
    .Y(_033_)
  );
  sky130_fd_sc_hd__nand2_1 _080_ (
    .A(_032_),
    .B(_033_),
    .Y(_034_)
  );
  sky130_fd_sc_hd__and3_1 _081_ (
    .A(A[0]),
    .B(_017_),
    .C(_021_),
    .X(_035_)
  );
  sky130_fd_sc_hd__and4b_1 _082_ (
    .A_N(current_state[2]),
    .B(current_state[0]),
    .C(current_state[1]),
    .D(C[0]),
    .X(_036_)
  );
  sky130_fd_sc_hd__a221o_1 _083_ (
    .A1(B[0]),
    .A2(_018_),
    .B1(_020_),
    .B2(D[0]),
    .C1(_036_),
    .X(_037_)
  );
  sky130_fd_sc_hd__o21a_1 _084_ (
    .A1(_035_),
    .A2(_037_),
    .B1(acc_reg[0]),
    .X(_038_)
  );
  sky130_fd_sc_hd__xor2_1 _085_ (
    .A(acc_reg[1]),
    .B(_034_),
    .X(_039_)
  );
  sky130_fd_sc_hd__maj3_1 _086_ (
    .A(acc_reg[1]),
    .B(_034_),
    .C(_038_),
    .X(_040_)
  );
  sky130_fd_sc_hd__xor2_1 _087_ (
    .A(acc_reg[2]),
    .B(_030_),
    .X(_041_)
  );
  sky130_fd_sc_hd__a21oi_1 _088_ (
    .A1(_040_),
    .A2(_041_),
    .B1(_031_),
    .Y(_042_)
  );
  sky130_fd_sc_hd__a211o_1 _089_ (
    .A1(_040_),
    .A2(_041_),
    .B1(_026_),
    .C1(_031_),
    .X(_043_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _090_ (
    .A(next_state[1]),
    .SLEEP(next_state[2]),
    .X(_044_)
  );
  sky130_fd_sc_hd__or4_1 _091_ (
    .A(acc_reg[3]),
    .B(_023_),
    .C(_024_),
    .D(_025_),
    .X(_045_)
  );
  sky130_fd_sc_hd__and2_0 _092_ (
    .A(_044_),
    .B(_045_),
    .X(_046_)
  );
  sky130_fd_sc_hd__a21oi_1 _093_ (
    .A1(_043_),
    .A2(_046_),
    .B1(acc_reg[4]),
    .Y(_047_)
  );
  sky130_fd_sc_hd__nor3_1 _094_ (
    .A(current_state[1]),
    .B(current_state[0]),
    .C(current_state[2]),
    .Y(_048_)
  );
  sky130_fd_sc_hd__and3_1 _095_ (
    .A(acc_reg[4]),
    .B(_043_),
    .C(_046_),
    .X(_049_)
  );
  sky130_fd_sc_hd__nor3_1 _096_ (
    .A(_047_),
    .B(_048_),
    .C(_049_),
    .Y(_001_[4])
  );
  sky130_fd_sc_hd__nand2b_1 _097_ (
    .A_N(_026_),
    .B(_045_),
    .Y(_050_)
  );
  sky130_fd_sc_hd__xnor2_1 _098_ (
    .A(_042_),
    .B(_050_),
    .Y(_051_)
  );
  sky130_fd_sc_hd__nor2_1 _099_ (
    .A(acc_reg[3]),
    .B(_044_),
    .Y(_052_)
  );
  sky130_fd_sc_hd__a211oi_1 _100_ (
    .A1(_044_),
    .A2(_051_),
    .B1(_052_),
    .C1(_048_),
    .Y(_001_[3])
  );
  sky130_fd_sc_hd__xnor2_1 _101_ (
    .A(_040_),
    .B(_041_),
    .Y(_053_)
  );
  sky130_fd_sc_hd__nor2_1 _102_ (
    .A(acc_reg[2]),
    .B(_044_),
    .Y(_054_)
  );
  sky130_fd_sc_hd__a211oi_1 _103_ (
    .A1(_044_),
    .A2(_053_),
    .B1(_054_),
    .C1(_048_),
    .Y(_001_[2])
  );
  sky130_fd_sc_hd__xnor2_1 _104_ (
    .A(_038_),
    .B(_039_),
    .Y(_055_)
  );
  sky130_fd_sc_hd__nor2_1 _105_ (
    .A(acc_reg[1]),
    .B(_044_),
    .Y(_056_)
  );
  sky130_fd_sc_hd__a211oi_1 _106_ (
    .A1(_044_),
    .A2(_055_),
    .B1(_056_),
    .C1(_048_),
    .Y(_001_[1])
  );
  sky130_fd_sc_hd__o21ai_0 _107_ (
    .A1(_035_),
    .A2(_037_),
    .B1(_044_),
    .Y(_057_)
  );
  sky130_fd_sc_hd__xor2_1 _108_ (
    .A(acc_reg[0]),
    .B(_057_),
    .X(_003_)
  );
  sky130_fd_sc_hd__nor2_1 _109_ (
    .A(_048_),
    .B(_003_),
    .Y(_001_[0])
  );
  sky130_fd_sc_hd__nand3b_1 _110_ (
    .A_N(current_state[1]),
    .B(current_state[0]),
    .C(current_state[2]),
    .Y(_004_)
  );
  sky130_fd_sc_hd__clkinv_1 _111_ (
    .A(_004_),
    .Y(_002_)
  );
  sky130_fd_sc_hd__mux2_1 _112_ (
    .A0(acc_reg[4]),
    .A1(F[4]),
    .S(_004_),
    .X(_000_[4])
  );
  sky130_fd_sc_hd__nand2_1 _113_ (
    .A(acc_reg[3]),
    .B(_002_),
    .Y(_005_)
  );
  sky130_fd_sc_hd__nand2_1 _114_ (
    .A(F[3]),
    .B(_004_),
    .Y(_006_)
  );
  sky130_fd_sc_hd__nand2_1 _115_ (
    .A(_005_),
    .B(_006_),
    .Y(_000_[3])
  );
  sky130_fd_sc_hd__nand2_1 _116_ (
    .A(acc_reg[2]),
    .B(_002_),
    .Y(_007_)
  );
  sky130_fd_sc_hd__nand2_1 _117_ (
    .A(F[2]),
    .B(_004_),
    .Y(_008_)
  );
  sky130_fd_sc_hd__nand2_1 _118_ (
    .A(_007_),
    .B(_008_),
    .Y(_000_[2])
  );
  sky130_fd_sc_hd__nand2_1 _119_ (
    .A(acc_reg[1]),
    .B(_002_),
    .Y(_009_)
  );
  sky130_fd_sc_hd__nand2_1 _120_ (
    .A(F[1]),
    .B(_004_),
    .Y(_010_)
  );
  sky130_fd_sc_hd__nand2_1 _121_ (
    .A(_009_),
    .B(_010_),
    .Y(_000_[1])
  );
  sky130_fd_sc_hd__nand2_1 _122_ (
    .A(acc_reg[0]),
    .B(_002_),
    .Y(_011_)
  );
  sky130_fd_sc_hd__nand2_1 _123_ (
    .A(F[0]),
    .B(_004_),
    .Y(_012_)
  );
  sky130_fd_sc_hd__nand2_1 _124_ (
    .A(_011_),
    .B(_012_),
    .Y(_000_[0])
  );
  sky130_fd_sc_hd__a31oi_1 _125_ (
    .A1(acc_reg[4]),
    .A2(_043_),
    .A3(_046_),
    .B1(acc_reg[5]),
    .Y(_013_)
  );
  sky130_fd_sc_hd__and4_1 _126_ (
    .A(acc_reg[4]),
    .B(acc_reg[5]),
    .C(_043_),
    .D(_046_),
    .X(_014_)
  );
  sky130_fd_sc_hd__nor3_1 _127_ (
    .A(_048_),
    .B(_013_),
    .C(_014_),
    .Y(_001_[5])
  );
  sky130_fd_sc_hd__mux2_1 _128_ (
    .A0(acc_reg[5]),
    .A1(F[5]),
    .S(_004_),
    .X(_000_[5])
  );
  sky130_fd_sc_hd__dfrtp_1 _129_ (
    .CLK(clk),
    .D(next_state[0]),
    .Q(current_state[0]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _130_ (
    .CLK(clk),
    .D(next_state[1]),
    .Q(current_state[1]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _131_ (
    .CLK(clk),
    .D(next_state[2]),
    .Q(current_state[2]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _132_ (
    .CLK(clk),
    .D(_000_[0]),
    .Q(F[0]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _133_ (
    .CLK(clk),
    .D(_000_[1]),
    .Q(F[1]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _134_ (
    .CLK(clk),
    .D(_000_[2]),
    .Q(F[2]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _135_ (
    .CLK(clk),
    .D(_000_[3]),
    .Q(F[3]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _136_ (
    .CLK(clk),
    .D(_000_[4]),
    .Q(F[4]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _137_ (
    .CLK(clk),
    .D(_000_[5]),
    .Q(F[5]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _138_ (
    .CLK(clk),
    .D(_002_),
    .Q(valid),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _139_ (
    .CLK(clk),
    .D(_001_[0]),
    .Q(acc_reg[0]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _140_ (
    .CLK(clk),
    .D(_001_[1]),
    .Q(acc_reg[1]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _141_ (
    .CLK(clk),
    .D(_001_[2]),
    .Q(acc_reg[2]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _142_ (
    .CLK(clk),
    .D(_001_[3]),
    .Q(acc_reg[3]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _143_ (
    .CLK(clk),
    .D(_001_[4]),
    .Q(acc_reg[4]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _144_ (
    .CLK(clk),
    .D(_001_[5]),
    .Q(acc_reg[5]),
    .RESET_B(rst_n)
  );
endmodule
